name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: actions-rs/toolchain@v1
    #   with:
    #       toolchain: nightly
    #       target: x86_64-fortanix-unknown-sgx
    # - name: Cargo Fmt
    #   run: cargo fmt --check
    # - name: Clippy 
    #   run: cargo clippy -- -D warnings
    # - name: Cargo Build Fortanix target
    #   run: cargo +nightly build --release --target x86_64-fortanix-unknown-sgx
    # - name: Run tests
    #   run: cargo test --verbose